# Render 配置文件
# 明确指定服务配置，避免自动检测错误

services:
  - type: web
    name: heart-rhythm-backend
    env: python
    region: oregon

    # Python 版本
    pythonVersion: "3.9"

    # 构建和运行命令
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py

    # 健康检查
    healthCheckPath: /docs

    # 免费方案
    plan: free
